//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ChannelFactory
{
    //Ändrade public virtual till static
	public static IChannel CreateChannel(string channelName)
	{
        //Skapa channels (RixFM & P3)
        IChannel channel = null;
        switch (channelName)
        {
            case "RixFM" :
                channel = new RixFM();
                break;

            case "P3":
                channel = new P3();
                break;
        }
        return channel;
	}

}

